import numpy as np

A=np.array([[2, 5, 7],[3, 4, 2],[5, 2, 3]])
B=np.array([23, 19, 20])
rangA=np.linalg.matrix_rank(A)
detA=np.linalg.det(A)
w, v=np.linalg.eig(A)
U=np.linalg.inv(A)
print("Matrix A:\n",A)
print("det A="+str(detA))
print("rang A="+str(rangA))
print("Eigen vals = ", w)
print("Eigen vectors = ", w)
print("Matrix U = inv(A):\n",U)
X1=np.linalg.solve(A, B)
print("Solution of  A*X1=B:\n",X1)
X2=U.dot(B)
print("Solution of  A*X2=B:\n",X2)
X3=np.dot(U, B)
print("Solution of  A*X3=B:\n",X3)
AT=np.transpose(A)
print("AT=\n",AT)
X1=np.linalg.solve(AT, B)
print("Solution of  AT*X1=B:\n",X1)
Am10=A*(-10)
print(" A*(-10)=\n",Am10)
Ap10=A+(10)
print(" A+(10)=\n",Ap10)
a1_1=A
a1_2=B
a2_1=a1_1+a1_2
print("A+B (1)=",a2_1)
a2_2=np.add(a1_1, a1_2)
print("A+B (2)=",a2_2)
